# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license

# Continuous Integration (CI) GitHub Actions tests broken link checker using https://github.com/lycheeverse/lychee
# Ignores the following status codes to reduce false positives:
#   - 401(Vimeo, 'unauthorized')
#   - 403(OpenVINO, 'forbidden')
#   - 429(Instagram, 'too many requests')
#   - 500(Zenodo, 'cached')
#   - 502(Zenodo, 'bad gateway')
#   - 999(LinkedIn, 'unknown status code')

name: Check Broken Repo links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # runs at 00:00 UTC every day
  push:
    branches:
      - main
      - gh-pages
  pull_request:
    branches:
      - main
      - gh-pages

jobs:
  Links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install lychee
        run: curl -sSfL "https://github.com/lycheeverse/lychee/releases/latest/download/lychee-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xz -C /usr/local/bin

      - name: Test Markdown and HTML links with retry
        uses: ultralytics/actions/retry@main
        with:
          timeout_minutes: 60
          retry_delay_seconds: 3
          retries: 2
          run: |
            rm -rf .lycheecache
            lychee \
            --scheme 'https' \
            --timeout 60 \
            --insecure \
            --accept 100..=103,200..=299,401,403,429,500,502,999 \
            --exclude-all-private \
            --exclude 'https?://(www\.)?(linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|tiktok\.com|fonts\.gstatic\.com|fonts\.googleapis\.com|url\.com|tesla\.com)' \
            --exclude-path '**/ci.yaml' \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36" \
            './**/*.md' \
            './**/*.html'

      - name: Test Website, Markdown, HTML, YAML, Python and Notebook links with retry
        if: github.event_name == 'workflow_dispatch'
        uses: ultralytics/actions/retry@main
        with:
          timeout_minutes: 60
          retry_delay_seconds: 3
          retries: 2
          run: |
            rm -rf .lycheecache
            lychee \
            --scheme 'https' \
            --timeout 60 \
            --insecure \
            --accept 100..=103,200..=299,401,403,429,500,502,999 \
            --exclude-all-private \
            --exclude 'https?://(www\.)?(linkedin\.com|twitter\.com|instagram\.com|kaggle\.com|tiktok\.com|fonts\.gstatic\.com|fonts\.googleapis\.com|url\.com|tesla\.com)' \
            --exclude-path '**/ci.yaml' \
            --github-token ${{ secrets.GITHUB_TOKEN }} \
            --header "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.6478.183 Safari/537.36" \
            './**/*.md' \
            './**/*.html' \
            './**/*.yml' \
            './**/*.yaml' \
            './**/*.py' \
            './**/*.ipynb'
